### ISSUE TITLE
Newline stripping of pathname needs fixing

### ISSUE THREAD

**Issue by AccidentallyTheCable** [Cobertos/unitypackage_extractor#1]
Current code will strip last char from the pathname entry, however it does not check to see if its actually a newline before doing so. This can result in files coming out with incorrect file extensions as the last letter is dropped. I did a hack to make it work for me, but this should definitely check to see if its a newline before dropping

---      pathname = pathname[:-1].decode("utf-8") #Remove the newling, and decode
+++   pathname = pathname.decode("utf-8") #Remove the newling, and decode

**Comment by Cobertos** [comment]
Ah, I'll patch this up tonight. Thanks for the report

**Comment by Cobertos** [comment]
Patched up and added a test #1
