### ISSUE TITLE
test_packageExtractWithUnicodePath fails on Windows

### ISSUE THREAD

**Issue by absolute-disappointment** [Cobertos/unitypackage_extractor#17]
https://github.com/Cobertos/unitypackage_extractor/blob/b9019c795ab56d5aa6a984f5a76617eb92a6bd07/tests/test_testPackage.py#L62

Need to pass `encoding="utf-8"` to `open()`, since the file is UTF-8, but the default encoding on Windows isn't UTF-8 but region dependent, e.g. Windows-1252 or Windows-932 (on Japanese systems). Right now it'll read it with the wrong encoding because `open()` will default to the system/environment encoding setting, so the test fails.

**Comment by Cobertos** [comment]
Commit made to fix in #15

**Comment by Cobertos** [comment]
PRs will now run in Windows as well
