### ISSUE TITLE
How can I compress the files back into unitypackage?

### ISSUE THREAD

**Issue by DataGreed** [Cobertos/unitypackage_extractor#2]
I've used this tool to decompress files, changed something, now I need to compress everything back. How can I achieve this?

**Comment by Cobertos** [comment]
This isn't supported by this tool. It only supports reading a `.unitypackage`, not writing. You should be able to do [this directly in Unity](https://docs.unity3d.com/2018.1/Documentation/Manual/HOWTO-exportpackage.html) if you import all the files in there.

Curious on your workflow/need though, might be a useful feature to have if you needed to batch process changes to `.unitypackage` files or something?

**Comment by Cobertos** [comment]
Closing as **Won't Fix** unless someone can make a good case for this feature/someone wants to implement it.
