### ISSUE TITLE
EXE will not work

### ISSUE THREAD

**Issue by Ribbons0121R121** [Cobertos/unitypackage_extractor#20]
"Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00004788 (most recent call first):"
this shows up for a few seconds after downloading and running, then the window auto closes
no matter what i run it from or to or how

**Comment by Cobertos** [comment]
Huh, never seen this error before.

Can you give me your version of Windows?  Is Python loaded on the machine you're using?

**Comment by Nik-Novak** [comment]
I can also confirm the tool is not working on Windows 10 Pro, both python and via cmd results in the program executing but hanging with no additional outputs for over 10 minutes on a 60mb file.

**Comment by Cobertos** [comment]
@Nik-Novak see #21, I believe your issue is different and as a workaround you can use `v1.0.0` if you trust the `.unitypackage` to not be malicious.

Closing this, will reopen if any new info
