### ISSUE TITLE
Does not work with attached package

### ISSUE THREAD

**Issue by oddgames-david** [Cobertos/unitypackage_extractor#3]
The extractor doesn't work with this package:

https://download.bugsee.com/sdk/unity/BugseeUnity-stable.unitypackage

**Comment by Cobertos** [comment]
Thanks for the report!

Looks like this is a weird case where the tar had a `./` preceding all the top level folders. Generated a test case for this using `tar -rf archtemp.tar .` and it gave a similar archive. Should have a fix shortly.

**Comment by Cobertos** [comment]
Aight, fixed in https://github.com/Cobertos/unitypackage_extractor/releases/tag/0.4.0
